name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Set Spotify API token 
        run: echo 'export SPOTIFY_API_TOKEN="${{ secrets.SPOTIFY_API_TOKEN }}"' >> $GITHUB_ENV

      - name: Run pytest
        run: poetry run pytest
